--- #YAML:1.0
name:                Gift
version:             0.8
abstract:            Parser for Moodle GIFT format for quizs
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casiano Rodriguez Leon casiano@ull.es
